plugins {
    id 'com.android.application'
}

android {
    namespace 'com.wangdian.quiz'
    compileSdk 34

    defaultConfig {
        applicationId "com.wangdian.quiz"
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file("release.keystore")
            storePassword "wangdian123"
            keyAlias "wangdian"
            keyPassword "wangdian123"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.webkit:webkit:1.8.0'
}
